### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by alrighttheresham** [tail-f-systems/JNC#1]
Feature Request to move from Ant to Maven Multiproject.  

Will allow support out of the box: 
- All IDE configuration files, Eclipse, IDEAJ, etc.
- Publishing of Milestone releases (versioning)
- Easier integration of 3rd party dependencies
- Std project layout

**Comment by SamirMinds007** [comment]
Hi Klacke my codition is same like Amy in my case i have to use mvn based library, if possible can i have one copy?

**Comment by jomiklos** [comment]
Should be "resolved" / irrelevant (after 5e0dccc604c454ece1b6c0e794733fcec69d892a) and moving to Gradle build system/packages/plugins.
