### ISSUE TITLE
NPE on getting attribute which doesn't exist

### ISSUE THREAD

**Issue by tsoihim** [tail-f-systems/JNC#137]
Hello.

I got null pointer exception on parsing rpc-reply when I tried to connect NETCONF Device (Arista EOS) with JNC.
I find out that EOS replies on my reqeust without message-id attribute.

So I checked the code below (Element.java) and find out that getAttrValue method could raise NPE.

    /**
     * Returns the string value of the named attribute. Returns
     * <code>null</code> if no such attribute is found or "" if no value is
     * given to the attribute.
     *
     * @param name The name of the attribute
     * @return String value of the attribute.
     */
    public String getAttrValue(String name) {
        return getAttr(name).getValue();
    } 

According to the comment, this method returns null if no given attribute is found.
However, it raises NPE since it calls getValue method from null.

**Comment by jomiklos** [comment]
I prepared tiny "fix" to address inconsistency in function description and its behavior:

```diff
diff --git a/src/main/java/com/tailf/jnc/Element.java b/src/main/java/com/tailf/jnc/Element.java
index ea240ec..32f990d 100644
--- a/src/main/java/com/tailf/jnc/Element.java
+++ b/src/main/java/com/tailf/jnc/Element.java
@@ -696,7 +696,8 @@ public class Element implements Cloneable, Serializable {
      * @return String value of the attribute.
      */
     public String getAttrValue(String name) {
-        return getAttr(name).getValue();
+        Attribute attr = getAttr(name);
+        return (attr != null) ? attr.getValue() : null;
     }

     /**
```

According to RFC the `message-id` parameter is mandatory in both `rpc` and `rpc-reply`. 
Can you test whether the fix helps to get a better error/behavior for the client in your case?
