### ISSUE TITLE
Question: Design of an subscriber based service using JNC

### ISSUE THREAD

**Issue by akhemka** [tail-f-systems/JNC#23]
Hi,
I am very new to JNC (a couple of days) and have been given the task to design a client which subscribes to a NetConf server and then gets back stream of data Asynchronously (Whenever the server has it ready). It would be great if someone could give me an overview of how can this be done.
Thanks,
Anuja.

**Comment by martin-volf** [comment]
Sorry for not responding earlier. Feel free to reopen if still relevant.
