### ISSUE TITLE
NPE in NodeSet

### ISSUE THREAD

**Issue by hshorter** [tail-f-systems/JNC#24]
Seeing a NPE in the NodeSet code. 

java.lang.NullPointerException
    at com.tailf.jnc.NodeSet.removeMember(NodeSet.java:120)

The method below is throwing this at if(e.equals(x)).

```
public boolean removeMember(Element x) {
    for (int i = 0; i < size(); i++) {
        final Element e = getElement(i);
        if (e.equals(x)) {
            remove(i);
            return true;
        }
    }
    return false;
}
```

It seems the size and actual elements are out of sync somehow.

**Comment by martin-volf** [comment]
The code is still there, but as far as I can tell, there is nothing wrong with it and the bug cannot be reproduced.
