### ISSUE TITLE
Implement equals in Element

### ISSUE THREAD

**Issue by liggetm** [tail-f-systems/JNC#25]
Element currently checks only name, namespace and value in equals().  For generated YangElements it would be better to implement a deeper equals().  This would certainly allow for easier unit testing.  Whenever two Elements come from different sources it is difficult to test for equality without resorting to using toXMLString() on each.  The following results in a false positive test pass:

``` java

configureTest();
instance.doSomethingResultingInEdit();
final ArgumentCaptor<Element> editConfigArg = ArgumentCaptor.forClass(Element.class);
verify(netconfSession).editConfig(editConfigArg.capture());
verify(netconfSession).closeSession();
Assert.assertEquals(expectedElement, editConfigArg.getValue());

```

Whereas this results correctly in a fail:

``` java

Assert.assertEquals(expectedElement.toXMLString(), editConfigArg.getValue().toXMLString());

```

whenever the captured argument is not exactly the same as expectedElement.  Compare() also results in a false positive.  Come back to me if you need further information.

**Comment by martin-volf** [comment]
This is not JNC's thing. Good code testability is important, but this goes well beyond that.
