### ISSUE TITLE
Not sure what netconf version is used by JNC

### ISSUE THREAD

**Issue by mrhegde** [tail-f-systems/JNC#33]
I am not sure what version of netconf is used by JNC. My server talks only Netconf 1.0. 
I do not get any response from the server; not even for the hello message. 
I skimmed through the code to find what version does JNC uses, but couldn't find any.

I need to know how I could instruct JNC to use netconf 1.0 only. I do not want it to use 1.1 internally.

If I connect another vendor's (MG-SOFT) client using "Auto-select" version I see the same behavior as that of JNC. However, if I specifically select version 1.0 in MG-Soft product I do get hello reply with a valid session-id. 

Both JNC and MG-Soft are using Ganymed SSH2.

**Comment by jomiklos** [comment]
Both NETCONF 1.0 and 1.1 are now supported with latest codebase (past 5e0dccc604c454ece1b6c0e794733fcec69d892a), 
and session can be initiated by specifying the session/device instance to (not) use `1.1`.

You can grep for `boolean use11` parameter in source  of JNC library, or `newSession()` call in examples with extra parameter...
