### ISSUE TITLE
Question: NETCONF server crashes using the NetconfSession.get("path")

### ISSUE THREAD

**Issue by ramukima** [tail-f-systems/JNC#35]
Following code makes the NETCONF server crash -

```
    DeviceUser duser = new DeviceUser("bobby", "admin", "admin");
        Device dev = new Device("mydev", duser, "localhost", 2022);

        try {
            dev.connect("bobby");
            dev.newSession("cfg");
            System.out.println(dev.getSession("cfg").get("/devices/device").toXMLString());
        }
        catch (Throwable e) {
            e.printStackTrace();
        }
        finally {
            dev.closeSession("cfg");
            dev.close();
        }
```

The question is - Is this a problem on the NETCONF server implementation or there is something in the client code that may be problematic here ?

Note that calls like these succeed without crashing the server -

```
dev.getSession("cfg").getConfig(NetconfSession.RUNNING, "/devices/device").toXMLString()
```

**Comment by jomiklos** [comment]
Closing as "ancient", possibly related to "NETCONF server, not JNC client" issue.
If the problem persists with latest JNC versions, and you suspect this is related to JNC's part, please create new ticket...
