### ISSUE TITLE
confdc fails to generate the XSD file in example 0-intro.

### ISSUE THREAD

**Issue by TatsuyaIwashita** [tail-f-systems/JNC#43]
Hi,
I met the error when trying to 'make' at step 4.1 in the example 0-intro README.

```
 $ LANG=C make all
 cp /home/ncs/ncs/netsim/confd/etc/confd/ietf-inet-types.fxs ietf-inet-types.fxs
 /home/ncs/ncs/netsim/confd/bin/confdc --java-package com.example.test -c ../../yang/hosts.yang
 /home/ncs/ncs/netsim/confd/bin/confdc -f /home/ncs/ncs/netsim/confd/etc/confd/ietf-inet-types.fxs \
--emit-xsd hosts.xsd hosts.fxs
 Internal error
 make: *** [hosts.xsd] Error 1
```

How do I see the details of the error?
The version is NCS 3.4.1 and confd-5.4.1.

Thanks.

**Comment by klacke** [comment]
It's an internal error, the error will mean nothing to you. it'll refer to internal structures.
To answer the q,

export CONFDC_PRINT_ERR=true

What's your confdc version

$ confdc --version

??

/klacke

**Comment by klacke** [comment]
It was the generation of .xsd files that was broken, There are better ways to do that now, using pyang directly instead of confdc. I removed the .xsd target entirely since it was not used at all.

Do a git pull and try again,

/klacke

**Comment by TatsuyaIwashita** [comment]
Thank you. The updated one worked well.
