### ISSUE TITLE
How to delete XPATH capabilities from JNC hello message

### ISSUE THREAD

**Issue by vivekiiitm1** [tail-f-systems/JNC#45]
We are using JNC along with Ganymed to communicate with HP 5900 switches which does not support XPATH. HPN support is asking us to delete the XPATH capability form client hello message.
5900 server capabilities - 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
<capability>urn:ietf:params:netconf:base:1.0</capability>
<capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
<capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
<capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
<capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
<capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
<capability>urn:hp:params:netconf:capability:hp-netconf-ext:1.0</capability>
<capability>urn:hp:params:netconf:capability:hp-save-point::1.0</capability>
</capabilities>
</hello>

We are newbies for JNC and don't know how JNC is sending hello message to server and how to remove XPATH capabilities from hello message? Ideally, they should auto - negotiate hello messages :(

Any help would be great for us to move forward and better understanding. Also, looks like, all JNC examples are heavily dependent on XPATH.

**Comment by klacke** [comment]
Interesting, an HP netconf implementation I'm unaware of. I have no experience with this device. It may be that the JNC and their NETCONF impl have some quirks working together.
Nevertheless, as for the actual XPATH capa, there is no negotiation going on, both ends send to the other what they're capable of, and it's up to the receiver to respect that.

And AFAIK, JNC doesn't send the xpath capa, typically the agent (server) sends it, and then it's
up to the client (JNC) to see and respect that. If the HP switch doesn't send xapth capa, it just means the if we want to do selective get-config RPC, we must use std subfilter, and not xpath

As for the JNC examples - no I'd say that few (any ??) of the examples are dependent on xpath.

So, I'd say that answer from HP support is strange.

To ensure NETCONF standard compliance, you could try to send some simple payloads using the 'ssh -s .... netconf' shell command . You could post those here if you want to.

**Comment by klacke** [comment]
See nothing happening here ...
