### ISSUE TITLE
XML output does not escape XML 'special' characters

### ISSUE THREAD

**Issue by peergynt** [tail-f-systems/JNC#48]
When writing a value which contains an XML character entity (for instance '&' in the string 'yin & yang'), JNC does not escape the '&' (the XML should be yin &amp; yang).
When JNC reads such data, the XML parser works fine and everything seems to be translated properly. But when writing to the netconf agent, the XML output does not follow XML standards. It looks like the XML is encoded 'by hand instead' of using an XML library.
I'm looking into replacing the manual XML generation with using JDOM if anyone is interested.

**Comment by klacke** [comment]
already fixed in #49
