### ISSUE TITLE
Some files are not generated correctly by pyang using jnc.py

### ISSUE THREAD

**Issue by mumtazh** [tail-f-systems/JNC#53]
I downloaded JNC and generated jnc.jar. However the compilation for examples/0-intro fails because there seems to be a problem in some of the files generated by pyang. When the generate target in build.xml is run by ant, it generates java files under src/gen/com/example/test. There are four directories here. All the other Java files seem to be OK, however package-info.java has each character on a new line. The compilation fails for package-info.java. I then removed package-info.java from under all these directories. The compilation worked after that. However when I do ant run, it fails and there is a parsing exception for Simple.schema. Simple.schema has the same problem as package-info.java. Every character is on a different line.

Does anyone know what could be source of this problem. Thanks.

**Comment by klacke** [comment]
Yes - I'm not really sure what we should do with the python code that generate Java. The NETCONF client part of JNC is just great, lot's of people use it - whereas the Java code generator isn't used by especially many projects (any ???)
I guess it's looking for a maintainer or at least someone who can give it some love.

**Comment by mumtazh** [comment]
Thanks for your response. 

Is this a known issue. Almost all the Java code that is being generated seems fine. Issue is with package-info.java and the .schema file. I think package-info.java is not really needed so I used one the jnc flags in pyang to not generate that file. However the JNC examples still use the .schema file (Simple.schema) and there is no way to get around that.

**Comment by mumtazh** [comment]
An update on this. On the suggestion of our contact in tail-f, I moved the jnc.py to the pyang plugin directory under confd. That fixed the problem and now the files are being generated correctly.

**Comment by klacke** [comment]
OK - awesome. If this happened while you followed the README, and the README was wrong - maybe you could provide an update ? Anyways - I close this.

**Comment by kaushik2306** [comment]
Hi Klacke/mumtazh,
I still see this issue ..Can some one help

**Comment by klacke** [comment]
I'm sorry, I'm no longer working with JNC. You'll have to poke some of the Cisco folks that are responsible now.

**Comment by kaushik2306** [comment]
Hi
It will good if you can share the jnc jar.  Thank you
chaudharikaushik@gmail.com
