### ISSUE TITLE
Roll back

### ISSUE THREAD

**Issue by Arunapotti** [tail-f-systems/JNC#57]
Hi klacke,

Is it possible to do a roll back of an editConfig after commit has been performed on the data stores? Does JNC has any api to support this? I have looked it up, but could not find one. I appreciate your response.

Thanks,
Aruna.

**Comment by klacke** [comment]
On 13/01/16 20:07, Arunapotti wrote:
>
> Hi klacke,
>
> Is it possible to do a roll back of an editConfig after commit has 
> been performed on the data stores? Does JNC has any api to support 
> this? I have looked it up, but could not find one I appreciate your 
> response
>
>

Not really no,  depending on what type of device you speak to and 
weather that
device has special actions to invoke last rollback, this might be possible.
ConfD has such actions, maybe Junipers do too.

The NETCONF protocol doesn't have any such capabilities.

One option is if the device has support for the candidate datastore, if
so, commit will "bite", but it'll rollback unless you eventually (within the
stipulated timeout) issue the final confirming-commit, which then
is sort of rolling back the last change.


/klacke

**Comment by Arunapotti** [comment]
Thanks Klacke for a quicker response.

I have been told our device has the roll back capabilities in candidate config data store. In that case, is it possible to do using a jnc api or you are saying if the device has the capability then access the device directly and perform the roll back. 

Also I am thinking, if I can do a backup of the config data store and restore the backup after the commit if needed to roll back. Is this possible with the below code snippet, 

Nodeset configData = getConfig()
Nodeset backup = configData.clone();
...
editConfig(configData )
commit
..
if(rollbackNeeded)
copyConfig(Element backup , int target)
..
Thanks,
Aruna.

**Comment by klacke** [comment]
If the device has the candidate data store, you can utilize that
as in:

editConfig(cfg);
commit();

if (rollbackNeeded)
   closeNetconfSession();
else
   confirmedCommit()
