### ISSUE TITLE
Can we use simple TCP connection in place of SSH?

### ISSUE THREAD

**Issue by vishwaraths** [tail-f-systems/JNC#60]
Can we use simple TCP connection to connect with confd server in place of SSH, if yes then which library i need to use to establish a plane connection, so that i can easily see the request data.

**Comment by klacke** [comment]
Yes - by implementing a TCPSession class that implements the Transport interface. I think
we had such a class earlier, but it looks as if it's been removed.

ConfD supports TCP, however this is not secure, the client TELLs ConfD which user/group it
is, assuming auth is already done.

If the purpose here is to be able to see what data gets sent on the wire, ConfD has tracing support.
Use that. Also JNC has cleartext payload support.

**Comment by vishwaraths** [comment]
Thanks for your quick response.
I will try your suggested way.

**Comment by vishwaraths** [comment]
Hi klacke,
How to enable clear text payload support in jnc?

**Comment by klacke** [comment]
As I wrote - not supported - you'd have to write "a TCPSession class that implements the Transport interface"
I also wrote - that since both JNC as well as ConfD supports clear text traffic tracing, you probably don't need this
