### ISSUE TITLE
Error while generating classes from yang file

### ISSUE THREAD

**Issue by ravirajsdeshmukh** [tail-f-systems/JNC#61]
I am trying to run example 02-junos and getting following error while generating classes from yang file.

TypeError: unsupported operand type(s) for +: 'JNCPlugin' and 'str'

Full Error Trace:

configuration-15.1.yang:6: warning: unexpected modulename "configuration" in configuration-15.1.yang, should be configuration-15.1
configuration-15.1.yang:9: error: module "junos-extension" not found in search path
configuration-15.1.yang:196 (at configuration-15.1.yang:4830): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:7494): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:9451): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:44948): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:47842): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:79904): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:117364): warning: default value for a key leaf is ignored
configuration-15.1.yang:196 (at configuration-15.1.yang:228181): warning: default value for a key leaf is ignored
WARNING: wbad_module_name, aborting.Traceback (most recent call last):
  File "/opt/python-2.7.3/bin/pyang", line 5, in <module>
    pkg_resources.run_script('pyang==1.6', 'pyang')
  File "/opt/python-2.7.3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/opt/python-2.7.3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/opt/python-2.7.3/lib/python2.7/site-packages/pyang-1.6-py2.7.egg/EGG-INFO/scripts/pyang", line 425, in <module>
    run()
  File "/opt/python-2.7.3/lib/python2.7/site-packages/pyang-1.6-py2.7.egg/EGG-INFO/scripts/pyang", line 402, in run
    sys.stderr.write(e.msg + '\n')
TypeError: unsupported operand type(s) for +: 'JNCPlugin' and 'str'

Regards,
Raviraj

**Comment by klacke** [comment]
I'm afraid the Python code that generates Java classes from Yang isn't maintained. We really should deprecated it or something until someone steps up to maintain that code.
The Java code, the actual netconf client lib is top notch though. Used by lots of folks.
