### ISSUE TITLE
JNC generates Java files with single-char per line

### ISSUE THREAD

**Issue by jiaofan** [tail-f-systems/JNC#64]
Hello,

We are using JNC to generate Java files from the yang files. But some of Java files generated are of single character per line. Please fix this.
[dellDns.tar.gz](https://github.com/tail-f-systems/JNC/files/221904/dellDns.tar.gz)

**Comment by klacke** [comment]
I'm afraid the code generator part of JNC isn't production ready. What's worse - it lacks a maintainer. I suggest you just skip the code generator, and use the client library directly instead. Much easier too.
