### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by 1smoot** [tail-f-systems/JNC#69]
I would appreciate it if you could upload notif.xml, I think it should be in tests/11-test-notification/".

**Comment by klacke** [comment]
Hmm,

This "test" seems to be very incomplete. It's not just the notif.xml 
that is missing, but more.

What's also missing from the "test" is ConfD code to actually generate
any notifications. So, even if we had some initalization code 
(notif.xml) to populate the ConfD /interfaces/interface list, we still
lack code to generate the notifcations.

Thus - incomplete.

Best path forward here - I guess - assuming you have access to a ConfD
is to take the ConfD example

examples.confd/netconf_notications

and add portions of that example to this example. The ConfD example use
netconf-console to create the subscription, whereas this code should use
the Java code in the tests/11-test-notification/ to subscribe.

That code looks correct BTW.

So all in all - there is some work left to get this example running.

This should work fine also with the "free" version of ConfD
https://developer.cisco.com/site/confD/

/klacke

**Comment by klacke** [comment]
Furthermore, I'm closing this issue. Someday, someone should spend a couple of days doing a full overhaul of these examples. Sorry.
