### ISSUE TITLE
NETCONF 1.1 compatibility

### ISSUE THREAD

**Issue by ReignInChaos** [tail-f-systems/JNC#70]
Enhance JNC to support Netconf 1.1 (RFC 6241, RFC 6242, etc)

**Comment by klacke** [comment]
I agree, this would be good. It's quite a bit of work though. Is there a particular 1.1 feature you are missing ?

**Comment by ReignInChaos** [comment]
After some preliminary testing, JNC does a capability check for netconf 1.0 and can't communicate with a 1.1 device.  Additionally, since 1.1 calls for chunked framing and not the delimiter ']]>]]>,' unpredictable behavior such as session closing and lack of rpc execution exists.  Simply changing the capability to 1.1 allows successful Hello exchange but previous consequences arise.

**Comment by klacke** [comment]
It's the agent then that is buggy. Which agent? It's the responsibility of a 1.1 agent to also be able to seamlessly talk to a pure 1.0 client. As per the RFC.
Correct, the chunking is different, as well as a few more things. I don't really have time now to enhance JNC to be a proper 1.0/1.1 client.

**Comment by Arunapotti** [comment]
Hi  ReignInChaos and  klacke  , how are we addressing this issue. I also have similar requirement where I need JNC to support NETCONF 1.1

**Comment by jomiklos** [comment]
this should be resolved now with PR #106 + merge to master after 5e0dccc604c454ece1b6c0e794733fcec69d892a
