### ISSUE TITLE
 module "tailf-common" not found in search path

### ISSUE THREAD

**Issue by sandeep-shenoy-mitel** [tail-f-systems/JNC#72]
Not able to compile JNC example 0-Intro .

Using Python-2.7/pyang 1.7. Below is the error trace, 

fails at below line in build.xml

pyang -f  jnc --verbose --jnc-output src/gen/com/example/test ../yang/hosts.yang. 

Please let me know if i am missing something

../yang/hosts.yang:5: error: module "tailf-common" not found in search path
../yang/hosts.yang:8: error: module "ietf-inet-types" not found in search path
Traceback (most recent call last):
  File "D:\Python27\Scripts\pyang", line 4, in <module>
    **import**('pkg_resources').run_script('pyang==1.7', 'pyang')
  File "D:\Python27\lib\site-packages\pkg_resources__init__.py", line 729, in r
un_script
    self.require(requires)[0].run_script(script_name, ns)
  File "D:\Python27\lib\site-packages\pkg_resources__init__.py", line 1642, in
run_script
    exec(code, namespace, namespace)
  File "d:\python27\lib\site-packages\pyang-1.7-py2.7.egg\EGG-INFO\scripts\pyang
", line 434, in <module>
    run()
  File "d:\python27\lib\site-packages\pyang-1.7-py2.7.egg\EGG-INFO\scripts\pyang
", line 411, in run
    sys.stderr.write(e.msg + '\n')
TypeError: unsupported operand type(s) for +: 'JNCPlugin' and 'str'

**Comment by xinpeng-chen** [comment]
add yangfiles path argument,
pyang --path /yangfiles/ -f jnc --verbose --jnc-output src/gen/com/example/test ../yang/hosts.yang

**Comment by jomiklos** [comment]
With latest codebase, examples are built & run via Gradle build system and above problem that existed before is IMHO not valid/relevant anymore.

**Comment by muralivenugopal** [comment]
@jomiklos, Im still facing the problem. 

Im using the Gadle build system. Where im going wrong. Please provide your input. 
Find the exception below and my platform details after that.


WARNING: illegal_escape_warn, aborting.Traceback (most recent call last):
  File "/home/murali/pyenvs/pyang/bin/pyang", line 549, in run
    emit_obj.emit(ctx, modules, fd)
  File "/home/murali/pyenvs/pyang/lib/python3.8/site-packages/pyang_jnc/jnc.py", line 192, in emit
    self.fatal("%s contains errors" % epos.top.arg)
  File "/home/murali/pyenvs/pyang/lib/python3.8/site-packages/pyang_jnc/jnc.py", line 280, in fatal
    raise error.EmitError(self, exitCode)
pyang.error.EmitError: (<pyang_jnc.jnc.JNCPlugin object at 0x7fe214bfea90>, 'tailf-common contains errors')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/murali/pyenvs/pyang/bin/pyang", line 580, in <module>
    run()
  File "/home/murali/pyenvs/pyang/bin/pyang", line 552, in run
    sys.stderr.write(e.msg + '\n')
TypeError: unsupported operand type(s) for +: 'JNCPlugin' and 'str'



My env details 
- Python 3.8.10
- pyang 2.5.3
- openjdk 11.0.17 2022-10-18
- git branch
* development
  master

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.17 (Ubuntu 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64
