### ISSUE TITLE
jnc.py generates files with line break after every character

### ISSUE THREAD

**Issue by FileIOUtility** [tail-f-systems/JNC#80]
jnc.py generates files with line break after every character, eg. all package-info.java and schema  files.
There seems to be a problem in the fragment:

     with open(d + os.sep + file_name, 'w+') as f:
        if isinstance(file_content, str):
            f.write(file_content)
        else:
            for line in file_content:
                f.write(line)
                f.write('\n')

**Comment by FileIOUtility** [comment]
Workaround in
https://github.com/FileIOUtility/JNC/blob/master/jnc.py

**Comment by martin-volf** [comment]
Not reproducible with recent changes.
