### ISSUE TITLE
Does method "Element create(String namespace, String pathStr)" support xpath which has multiple conditions ?

### ISSUE THREAD

**Issue by buddha1987** [tail-f-systems/JNC#88]
I try to use Element.create() to create an element from a Xpath which has multiple conditions, e.g.:
xPath = "/a/b/c/[d=1 and e=2]".
In this case, I got error :
"Error in path: parse error: Error in path: parse error: 
	at com.tailf.jnc.Path.parse(Unknown Source)
	at com.tailf.jnc.PathCreate.<init>(Unknown Source)
	at com.tailf.jnc.Element.create(Unknown Source)
	at com.tailf.jnc.Element.create(Unknown Source)"

It looks like can't parse the Xpath with multiple conditions. Is there any way that Element.create can support that ?

Thanks.

**Comment by kaposnick** [comment]
Try something like this:

xPath = "/a/b/c[d=1][e=2]. 

This is supported.

**Comment by martin-volf** [comment]
Closing. The workaround described by @kaposnick should be enough.
