### ISSUE TITLE
Error while generating java class from Yang

### ISSUE THREAD

**Issue by yu-zhang** [tail-f-systems/JNC#89]
generate:
    [mkdir] Created dir: /JNC/JNC/examples/0-intro/src/gen
    [mkdir] Created dir: /JNC/JNC/examples/0-intro/src/gen/com
    [mkdir] Created dir: /JNC/examples/0-intro/src/gen/com/example
    [mkdir] Created dir: /JNC/examples/0-intro/src/gen/com/example/test
    [mkdir] Created dir: /JNC/examples/0-intro/src/gen/com/example/test/inet
     [exec] Traceback (most recent call last):
     [exec]   File "/JNC/pyang/pyang/bin/pyang", line 493, in <module>
     [exec]     run()
     [exec]   File "/JNC/pyang/pyang/bin/pyang", line 465, in run
     [exec]     sys.stderr.write(e.msg + '\n')
     [exec] TypeError: unsupported operand type(s) for +: 'JNCPlugin' and 'str'

**Comment by krishnact** [comment]
I was getting same error with python 3. Use this tool with python 2 and it works.

**Comment by chrisinmtown** [comment]
@yu-zhang  please post the python version you used, and if it worked for you, which 2.x version.

**Comment by jomiklos** [comment]
This might have been caused by previously unsupported python3/pyang compatibility. 
If the issue is still observed with latest JNC codebase (commit 5e0dccc604c454ece1b6c0e794733fcec69d892a or later), please create new issue with details on used versions of pyang/python etc.
